// Do not edit this file, it is auto-generated!

import AzzasHandmade from "./azzas-handmade";
import Bend24 from "./bend-24";
import ElectrosafeWarehouse from "./electrosafe-warehouse";
import LectroLED from "./lectro-led";
import LectroAccounting from "./lectro-accounting";
import Bend23 from "./bend-23";
import MonsteraSpeeduino from "./monstera-speeduino";
import NedapWanda from "./nedap-wanda";
import NedapLuna from "./nedap-luna";
import SmallSizeHolland from "./small-size-holland";

export const projectsComponents = [
  { 
    component: <AzzasHandmade />,
    path: "/azzas-handmade",
  },
  { 
    component: <Bend24 />,
    path: "/bend-24",
  },
  { 
    component: <ElectrosafeWarehouse />,
    path: "/electrosafe-warehouse",
  },
  { 
    component: <LectroLED />,
    path: "/lectro-led",
  },
  { 
    component: <LectroAccounting />,
    path: "/lectro-accounting",
  },
  { 
    component: <Bend23 />,
    path: "/bend-23",
  },
  { 
    component: <MonsteraSpeeduino />,
    path: "/monstera-speeduino",
  },
  { 
    component: <NedapWanda />,
    path: "/nedap-wanda",
  },
  { 
    component: <NedapLuna />,
    path: "/nedap-luna",
  },
  { 
    component: <SmallSizeHolland />,
    path: "/small-size-holland",
  },
];
