// Do not edit this file, it is auto-generated!

import AzzasHandmade from "./azzas-handmade";
import Bend24 from "./bend-24";
import ElectrosafeWarehouse from "./electrosafe-warehouse";
import LectroLED from "./lectro-led";
import LectroAccounting from "./lectro-accounting";
import Bend23 from "./bend-23";
import NedapWanda from "./nedap-wanda";
import NedapLuna from "./nedap-luna";
import SmallSizeHolland from "./small-size-holland";
import Bouklao from "./bouklao";
import Wordle from "./wordle";
import FHIRPlayground from "./fhir-playground";

export const projectsComponents = [
  { component: <Bouklao />, path: "/bouklao" },
  { component: <Wordle />, path: "/wordle" },
  { component: <FHIRPlayground />, path: "/fhir-playground" },
  {
    component: <AzzasHandmade />,
    path: "/azzas-handmade",
  },
  {
    component: <Bend24 />,
    path: "/bend-24",
  },
  {
    component: <ElectrosafeWarehouse />,
    path: "/electrosafe-warehouse",
  },
  {
    component: <LectroLED />,
    path: "/lectro-led",
  },
  {
    component: <LectroAccounting />,
    path: "/lectro-accounting",
  },
  {
    component: <Bend23 />,
    path: "/bend-23",
  },
  {
    component: <NedapWanda />,
    path: "/nedap-wanda",
  },
  {
    component: <NedapLuna />,
    path: "/nedap-luna",
  },
  {
    component: <SmallSizeHolland />,
    path: "/small-size-holland",
  },
];
